plugins {
    id 'com.android.application'
}
android {
    namespace 'com.parktube.aabrowser'
    compileSdk 35
    defaultConfig {
        applicationId 'com.parktube.aabrowser'
        minSdk 30
        targetSdk 35
        versionCode 7
        versionName '2.0.0'
    }
    buildTypes { release { minifyEnabled false } }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
