plugins {
    id 'com.android.application'
}
android {
    namespace 'com.parktube.aabrowser'
    compileSdk 35
    defaultConfig {
        applicationId 'com.pwk.parktube'
        minSdk 30
        targetSdk 35
        versionCode 12
        versionName '2.5.0'
    }
    buildTypes { release { minifyEnabled false } }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.media:media:1.8.0'
}
